### PR TITLE
update title for enrich sidebar & minor fixes

### LINKED ISSUE #2153: Enrich sidebar update text

### PR DESCRIPTION
**Pull request by maleksal**
- resolves #2153

### CODE REVIEW

File: frontend/src/components/Mining/EnrichGdprSidebar.vue [hunk 1]
```diff
@@ -68,7 +66,7 @@ const $screenStore = useScreenStore();
 const $profile = useSupabaseUserProfile();
 
 const drawer = ref();
-const visible = ref(false);
+const visible = ref(true);
```
Comment (J43fura) [inline frontend/src/components/Mining/EnrichGdprSidebar.vue:69]: Dont forget to undo this

**Review by J43fura — CHANGES_REQUESTED** [review]

**Review by J43fura — APPROVED** [review]
