### PR TITLE
Fix Anti-pattern: (JS-0357) 

### LINKED ISSUE #2027: Anti-pattern: (JS-0357) detected the use of variables before they are defined
### Description

Variables, functions and types should always be used after they've been defined. This issue will flag any code snippets that use variables or types before definition.

Sometimes, the code will run just fine even when the variable is declared after use. Consider the following example:
```ts
const ram: Resource = { type: "memory", limit: 1024 ** 3 }
type Resource = {
  type: string;
  limit: number;
}
```
Here, Resource is used in the annotation before it has been defined. Similarly, it is possible to hoist function declarations and variables declared with the var keyword:
```ts
const four = twice(2);
function twice(n: number) {
  return n * 2;
}
```
However, it makes the code harder to follow when variables or types are declared after being used.

### Occurrences

https://github.com/ankaboot-source/leadminer/blob/f43c55456f211f09570b7b11252635b52422c36b/frontend/src/stores/stepper.ts#L10-L10

https://github.com/ankaboot-source/leadminer/blob/f43c55456f211f09570b7b11252635b52422c36b/frontend/src/plugins/sb-optimize-cookie.ts#L88-L88

## Guidelines
Reference the issue in your PR description, to [close it automatically when your PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue)

### PR DESCRIPTION
**Pull request by MohamedAziz-Hammami**
This PR resolves #2027

### CODE REVIEW

File: frontend/src/plugins/sb-optimize-cookie.ts [hunk 1]
```diff
@@ -84,7 +84,6 @@ function stringToBase64URL(str: string) {
       queuedBits -= 6;
     }
   };
-
   stringToUTF8(str, emitter);
```
Comment (maleksal) [inline frontend/src/plugins/sb-optimize-cookie.ts:87]: Nothing changed in this function, is it used before it was defined ?

Comment (MohamedAziz-Hammami) [reply frontend/src/plugins/sb-optimize-cookie.ts:87]: yes

Comment (maleksal) [reply frontend/src/plugins/sb-optimize-cookie.ts:87]: If it's used before definition, then you need to change its place

Comment (maleksal) [reply frontend/src/plugins/sb-optimize-cookie.ts:87]: You need to place stringToUTF8 and the function above it on top of stringToBase64URL

**Review by maleksal — APPROVED** [review]
