### PR TITLE
fix misleading extraction notificaiton

### LINKED ISSUE #2138: misleading extraction notification
Image

### PR DESCRIPTION
**Pull request by J43fura**
- fix #2138 
image

### CODE REVIEW

File: frontend/src/components/Mining/StepperPanels/MinePanel.vue [hunk 1]
```diff
@@ -357,7 +356,7 @@ async function haltMining() {
     "back": "Back",
     "mined_total_emails": "Mined / Total emails\n{extractedEmails} / {totalEmails}",
     "mining_done": "Mining done",
-    "contacts_extracted": "{extractedEmails} contacts extracted from your mailbox",
+    "contacts_extracted": "{extractedEmails} email messages extracted from your mailbox",
```
Comment (maleksal) [inline frontend/src/components/Mining/StepperPanels/MinePanel.vue:359]: Should be contacts extracted, replace the value with createdContacts

**Review by maleksal — CHANGES_REQUESTED** [review]

**Review by maleksal — APPROVED** [review]
