### PR TITLE
fix: mailercheck verifier class quality issues 

### LINKED ISSUE #2186: Fix backend/src/services/email-status/mailercheck/index.ts quality issues
https://codeclimate.com/repos/63f7174b3d043100a803ee03/backend/src/services/email-status/mailercheck/index.ts/source#issue-badb3b857377da4d0453ae107cf94fb8

### PR DESCRIPTION
**Pull request by maleksal**
- resolves #2186

### CODE REVIEW

File: backend/src/services/email-status/mailercheck/index.ts [hunk 1]
```diff
@@ -85,30 +76,44 @@ export default class MailerCheckEmailStatusVerifier
...
+
   private pollVerificationStatus(listId: number) {
     return new Promise<boolean>((resolve) => {
       let failedSuccessivePollAttempts = 0;
       const interval = setInterval(async () => {
-        try {
-          const verificationStatus =
-            await this.mailerCheckClient.getListStatus(listId);
+        const success = await this.checkListStatus(listId);
+        if (success === false) {
```
Comment (J43fura) [inline backend/src/services/email-status/mailercheck/index.ts:107]: checkListStatus returns `true` or `null` according to the function code, it cannot return false, verify this

**Review by J43fura — CHANGES_REQUESTED** [review]
