### PR TITLE
Fix bulk enrichment notification

### LINKED ISSUE #1943: When bulk enrich, show a toast "Enrich on 12 contacts has started. Please wait a few minutes ☕"

### PR DESCRIPTION
**Pull request by maleksal**
- resolves #1943

### CODE REVIEW

File: frontend/src/components/Mining/Buttons/EnrichButton.vue [hunk 1]
```diff
@@ -391,7 +392,8 @@ const isEnrichDisabled = computed(
     "confirm_enrichment": "Confirm contact enrichment | Confirm {n} contacts enrichment",
     "notification": {
       "summary": "",
```
Comment (J43fura) [inline frontend/src/components/Mining/Buttons/EnrichButton.vue:394]: `summary` is empty, remove it if its unused

**Review by J43fura — APPROVED** [review]
