### PR TITLE
Fix datatable realtime

### LINKED ISSUE #2099: Cleaning finished but table is still being populated/changing

### PR DESCRIPTION
**Pull request by maleksal**
- resolves #2099

### CODE REVIEW

File: frontend/src/stores/contacts.ts [hunk 1]
```diff
@@ -18,15 +17,14 @@ export const useContactsStore = defineStore('contacts-store', () => {
   const selectedContactsCount = ref<number>(0);
 
   const contactCount = computed(() => contactsList.value?.length);
-  const isMiningTaskActive = computed(() => $leadminerStore.activeTask);
```
Comment (J43fura) [inline frontend/src/stores/contacts.ts:20]: Is being used in line 128

**Review by J43fura — CHANGES_REQUESTED** [review]

**Review by J43fura — APPROVED** [review]
